add docker support
madMAx43v3r/chia-gigahorse pull request #114
Opened 2023-05-09 00:54 UTC by Ac3sRwild

2023-05-09 09:02 UTC, felixbrucker requested changes
Nice work!

2023-05-11 08:46 UTC, madMAx43v3r commented
Ready to merge? I cannot test it myself...

2023-05-11 12:11 UTC, Ac3sRwild commented
Yes I made the changes recommended by felix so this should be all set to merge

2023-05-11 12:53 UTC, madMAx43v3r commented
great thx

2023-05-11 12:54 UTC, merged